-- AUTO-GENERATED by Scripts/build_all_class_expectations.py
-- DO NOT EDIT BY HAND.  Re-run the generator after Progressions.lsx changes.
-- Loaded by BootstrapServer.lua and exposed as _G.ApotheosisClassExpectations.

local M = { classes = {}, subclasses = {} }

M.classes["Artificer"] = {
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
            selectors = "SelectSpells(d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a,1,0,ArtificerSpellList)",
        },
        [14] = {
            passives  = { "Artificer_MagicItemSavant" },
            selectors = "SelectPassives(e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b,1,ArtificerInfusions)",
        },
        [15] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5)",
            selectors = "SelectSpells(d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a,1,0,ArtificerSpellList)",
        },
        [18] = {
            passives  = { "Artificer_MagicItemMaster" },
            boosts    = "ActionResource(SpellSlot,1,5)",
            selectors = "SelectPassives(e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b,1,ArtificerInfusions)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5)",
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Artificer_SoulOfArtifice" },
        },
    },
}

M.classes["Barbarian"] = {
    levels = {
        [12] = {
            passives  = {},
            boosts    = "ActionResource(Rage,1,0)",
        },
        [13] = {
            passives  = { "Barbarian_BrutalStrike_Improved" },
            boosts    = "ActionResource(RageCharge,1,0)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Barbarian_PersistentRage" },
        },
        [16] = {
            passives  = {},
            boosts    = "ActionResource(RageCharge,1,0)",
        },
        [17] = {
            passives  = { "Barbarian_BrutalStrike_17" },
        },
        [18] = {
            passives  = { "Barbarian_IndomitableMight" },
            boosts    = "ActionResource(RageCharge,1,0)",
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Barbarian_PrimalChampion" },
        },
    },
}

M.classes["Bard"] = {
    levels = {
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00170001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00180001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00190001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
        [18] = {
            passives  = { "Bard_SuperiorInspiration" },
            boosts    = "ActionResource(SpellSlot,1,5);ActionResource(BardicInspiration,1,0)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00190001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6)",
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons);SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00190001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
        [20] = {
            passives  = { "Bard_WordsOfCreation" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00190001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
    },
}

M.classes["Cleric"] = {
    levels = {
        [12] = {
            passives  = {},
        },
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "AddSpells(00170001-0001-0001-0001-000000000003)",
        },
        [14] = {
            passives  = { "ImprovedBlessedStrikes" },
        },
        [15] = {
            passives  = { "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8)",
            selectors = "AddSpells(00180001-0001-0001-0001-000000000003)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9)",
            selectors = "AddSpells(00190001-0001-0001-0001-000000000003)",
        },
        [18] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5);ActionResource(ChannelDivinity,1,0)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6)",
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Cleric_GreaterDivineIntervention" },
            boosts    = "ActionResource(SpellSlot,1,7)",
        },
    },
}

M.classes["Druid"] = {
    levels = {
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "AddSpells(00170001-0001-0001-0001-000000000004)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Druid_ImprovedElementalFury", "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8)",
            selectors = "AddSpells(00180001-0001-0001-0001-000000000004)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9)",
            selectors = "AddSpells(00190001-0001-0001-0001-000000000004)",
        },
        [18] = {
            passives  = { "Druid_BeastSpells" },
            boosts    = "ActionResource(SpellSlot,1,5)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6)",
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Druid_Archdruid" },
            boosts    = "ActionResource(SpellSlot,1,7);ActionResource(WildShape,100,0)",
        },
    },
}

M.classes["Fighter"] = {
    levels = {
        [13] = {
            passives  = { "Fighter_StudiedAttacks" },
            boosts    = "ActionResource(Indomitable_Charge,1,0)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = {},
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(ActionSurge,1,0);ActionResource(Indomitable_Charge,1,0)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "ExtraAttack_3" },
        },
    },
}

M.classes["Gunslinger"] = {
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectPassives(f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c,1,TrickShots)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Gunslinger_LightningReload" },
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(Risk,1,0)",
            selectors = "SelectPassives(f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7c,1,TrickShots)",
        },
        [18] = {
            passives  = { "Gunslinger_ViciousIntent" },
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Gunslinger_HemorrhagingCritical" },
            boosts    = "ActionResource(Risk,1,0)",
        },
    },
}

M.classes["Illrigger"] = {
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
            selectors = "SelectSpells(a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8d,1,0,IllriggerSpellList)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Illrigger_InfernalConduit" },
            boosts    = "ActionResource(Seal,1,0)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5)",
            selectors = "SelectSpells(a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8d,1,0,IllriggerSpellList)",
        },
        [18] = {
            passives  = {},
            boosts    = "ActionResource(Seal,1,0)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5)",
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Illrigger_PrinceOfHell" },
        },
    },
}

M.classes["Monk"] = {
    levels = {
        [13] = {
            passives  = { "Monk_DeflectEnergy" },
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [14] = {
            passives  = { "Monk_DisciplinedSurvivor" },
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [15] = {
            passives  = { "Monk_PerfectFocus" },
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [16] = {
            passives  = {},
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [18] = {
            passives  = { "Monk_SuperiorDefense" },
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(KiPoint,1,0)",
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Monk_BodyAndMind" },
            boosts    = "ActionResource(KiPoint,1,0);Ability(Dexterity,2,22);Ability(Wisdom,2,22)",
        },
    },
}

M.classes["MonsterHunter"] = {
    levels = {
        [13] = {
            passives  = { "MonsterHunter_13_LethalQuarry" },
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "MonsterHunter_15_PrimalAccuracy" },
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "MonsterHunter_17_HardenedResolve" },
        },
        [18] = {
            passives  = { "MonsterHunter_18_ApexPredator" },
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "MonsterHunter_20_MasterHunter" },
        },
    },
}

M.classes["Paladin"] = {
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
            selectors = "SelectSpells(4a614e36-b7af-4e84-9d44-7c6ab4ad884f,1,0,PaladinSpellList)",
        },
        [14] = {
            passives  = { "Paladin_CleansingTouch" },
        },
        [15] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4);ActionResource(SpellSlot,1,5)",
        },
        [18] = {
            passives  = { "Paladin_Aura30ft" },
            boosts    = "ActionResource(SpellSlot,1,5)",
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.classes["Ranger"] = {
    levels = {
        [13] = {
            passives  = { "Ranger_RelentlessHunter" },
            boosts    = "ActionResource(SpellSlot,1,4)",
            selectors = "SelectSpells(8a34b59f-b7ac-4283-a4cb-2c5e4e1f2e91,1,0,RangerSpellList)",
        },
        [14] = {
            passives  = {},
            selectors = "SelectPassives(eb28ac6c-0a84-4d94-bce6-a2c2caa9ae56,1,FavoredEnemy)",
        },
        [15] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4);ActionResource(SpellSlot,1,5)",
        },
        [18] = {
            passives  = { "Ranger_FeralSenses" },
            boosts    = "ActionResource(SpellSlot,1,5)",
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Ranger_FoeSlayer" },
        },
    },
}

M.classes["Rogue"] = {
    levels = {
        [13] = {
            passives  = { "Rogue_SubtleStrikes" },
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Rogue_SlipperyMind" },
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
        },
        [18] = {
            passives  = { "Rogue_Elusive" },
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Rogue_StrokeOfLuck" },
        },
    },
}

M.classes["Sorcerer"] = {
    levels = {
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7);ActionResource(SorceryPoint,1,0)",
            selectors = "SelectSpells(00170001-0001-0001-0001-000000000002,1,0,SorcererSpell)",
        },
        [14] = {
            passives  = {},
            boosts    = "ActionResource(SorceryPoint,1,0)",
            selectors = "SelectSpells(00170001-0001-0001-0001-000000000002,1,0,SorcererSpell)",
        },
        [15] = {
            passives  = { "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8);ActionResource(SorceryPoint,1,0)",
            selectors = "SelectSpells(00180001-0001-0001-0001-000000000002,1,0,SorcererSpell)",
        },
        [16] = {
            passives  = {},
            boosts    = "ActionResource(SorceryPoint,1,0)",
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9);ActionResource(SorceryPoint,1,0)",
            selectors = "SelectSpells(00190001-0001-0001-0001-000000000002,1,0,SorcererSpell);SelectPassives(c3506532-36eb-4d18-823e-497a537a9619,1,Metamagic)",
        },
        [18] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5);ActionResource(SorceryPoint,1,0)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6);ActionResource(SorceryPoint,1,0)",
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Sorcerer_ArcaneApotheosis" },
            boosts    = "ActionResource(SpellSlot,1,7);ActionResource(SorceryPoint,1,0)",
        },
    },
}

M.classes["Warlock"] = {
    levels = {
        [13] = {
            passives  = { "Warlock_MysticArcanum_7" },
            selectors = "SelectSpells(00170001-0001-0001-0001-000000000007,1,0,MysticArcanum7)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Warlock_MysticArcanum_8" },
            selectors = "SelectSpells(00180001-0001-0001-0001-000000000007,1,0,MysticArcanum8);SelectPassives(ab56f79f-95ec-48e5-bd83-e80ba9afc844,1,WarlockInvocations)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "Warlock_MysticArcanum_9" },
            selectors = "SelectSpells(00190001-0001-0001-0001-000000000007,1,0,MysticArcanum9)",
        },
        [18] = {
            passives  = {},
            selectors = "SelectPassives(ab56f79f-95ec-48e5-bd83-e80ba9afc844,1,WarlockInvocations)",
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Warlock_EldritchMaster" },
        },
    },
}

M.classes["Wizard"] = {
    levels = {
        [12] = {
            passives  = {},
            selectors = "SelectSpells(bc917f22-7f71-4a25-9a77-7d2f91a96a65,2,0)",
        },
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "SelectSpells(00170001-0001-0001-0001-000000000001,1,0,WizardSLevel7);SelectSpells(bc917f22-7f71-4a25-9a77-7d2f91a96a65,1,0,WizardSpellList)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8)",
            selectors = "SelectSpells(bc917f22-7f71-4a25-9a77-7d2f91a96a65,1,0,WizardSpellList);SelectSpells(00180001-0001-0001-0001-000000000001,1,0,WizardSLevel8)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9)",
            selectors = "SelectSpells(bc917f22-7f71-4a25-9a77-7d2f91a96a65,2,0,WizardSpellList)",
        },
        [18] = {
            passives  = { "SpellMastery" },
            boosts    = "ActionResource(SpellSlot,1,5)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6)",
            selectors = "SelectPassives(da3e7815-685b-469c-9bba-0f5a7cc93fd1,1,EpicBoons)",
        },
        [20] = {
            passives  = { "Wizard_SignatureSpells" },
            boosts    = "ActionResource(SpellSlot,1,7);ActionResource(SignatureSpellCharge,2,0)",
        },
    },
}

M.subclasses["AberrantSorcery"] = {
    parent = "Sorcerer",
    levels = {
        [14] = {
            passives  = { "AberrantSorcery_14_RevelationInFlesh" },
        },
        [18] = {
            passives  = { "AberrantSorcery_18_WarpingImplosion" },
        },
    },
}

M.subclasses["AbjurationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(7bd7b3ea-51da-4144-b5ba-3d85dbf79353,1,0,AbjurationSavant,,,AlwaysPrepared)",
        },
        [14] = {
            passives  = { "Abjurer_14_SpellResistance" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(7bd7b3ea-51da-4144-b5ba-3d85dbf79353,1,0,AbjurationSavant,,,AlwaysPrepared)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(7bd7b3ea-51da-4144-b5ba-3d85dbf79353,1,0,AbjurationSavant,,,AlwaysPrepared)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectSpells(7bd7b3ea-51da-4144-b5ba-3d85dbf79353,1,0,AbjurationSavant,,,AlwaysPrepared)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["Alchemist"] = {
    parent = "Artificer",
    levels = {
        [15] = {
            passives  = { "Alchemist_15_ChemicalMastery" },
        },
    },
}

M.subclasses["Ancients"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "Ancients_15_UndyingSentinel" },
        },
        [20] = {
            passives  = { "Ancients_20_ElderChampion" },
        },
    },
}

M.subclasses["ArcaneTrickster"] = {
    parent = "Rogue",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "ArcaneTrickster_VersatileTrickster" },
        },
        [17] = {
            passives  = { "ArcaneTrickster_11_SpellThief" },
        },
    },
}

M.subclasses["Archfey"] = {
    parent = "Warlock",
    levels = {
        [14] = {
            passives  = { "Archfey_14_BewitchingMagic" },
        },
    },
}

M.subclasses["ArchitectOfRuin"] = {
    parent = "Illrigger",
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [15] = {
            passives  = { "ArchitectsOfRuin_15_VileTransmogrification" },
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [18] = {
            passives  = { "ArchitectsOfRuin_18_HellMage" },
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [20] = {
            passives  = {},
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
    },
}

M.subclasses["Armorer"] = {
    parent = "Artificer",
    levels = {
        [15] = {
            passives  = { "Armorer_15_PerfectedArmor" },
        },
    },
}

M.subclasses["Artillerist"] = {
    parent = "Artificer",
    levels = {
        [15] = {
            passives  = { "Artillerist_15_FortifiedPosition" },
        },
    },
}

M.subclasses["Assassin"] = {
    parent = "Rogue",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "Assassin_InfiltrationExpertise" },
        },
        [17] = {
            passives  = { "Assassin_11_DeathStrike" },
        },
    },
}

M.subclasses["BattleMaster"] = {
    parent = "Fighter",
    levels = {
        [15] = {
            passives  = { "BattleMaster_Relentless" },
        },
        [18] = {
            passives  = {},
            boosts    = "ActionResource(SuperiorityDie,1,0)",
            selectors = "SelectPassives(a1b2c3d4-e5f6-7890-abcd-ef1234567890,1,CombatManeuvers)",
        },
    },
}

M.subclasses["BattleSmith"] = {
    parent = "Artificer",
    levels = {
        [15] = {
            passives  = { "BattleSmith_15_ImprovedDefender" },
        },
    },
}

M.subclasses["BeastMaster"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "BeastMaster_15_ShareSpells" },
        },
    },
}

M.subclasses["BerserkerPath"] = {
    parent = "Barbarian",
    levels = {
        [10] = {
            passives  = { "Berserker_10_Retaliation" },
        },
        [14] = {
            passives  = { "Berserker_14_IntimidatingPresence" },
        },
    },
}

M.subclasses["BladesingingSchool"] = {
    parent = "Wizard",
    levels = {
        [12] = {
            passives  = {},
        },
        [13] = {
            passives  = {},
        },
        [14] = {
            passives  = { "SongVictory" },
        },
        [15] = {
            passives  = {},
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["CarverGuild"] = {
    parent = "MonsterHunter",
    levels = {
        [15] = {
            passives  = { "CarverGuild_15_Bulwark" },
        },
        [18] = {
            passives  = { "CarverGuild_18_Executioner" },
        },
    },
}

M.subclasses["Celestial"] = {
    parent = "Warlock",
    levels = {
        [14] = {
            passives  = { "Celestial_14_SearingVengeance" },
        },
    },
}

M.subclasses["Champion"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "SuperiorCritical" },
        },
        [18] = {
            passives  = { "Champion_Survivor" },
        },
    },
}

M.subclasses["CircleOfStars"] = {
    parent = "Druid",
    levels = {
        [14] = {
            passives  = { "CircleOfStars_14_FullOfStars" },
        },
    },
}

M.subclasses["CircleOfTheLand"] = {
    parent = "Druid",
    levels = {
        [14] = {
            passives  = { "CircleOfTheLand_14_NaturesSanctuary" },
        },
    },
}

M.subclasses["CircleOfTheMoon"] = {
    parent = "Druid",
    levels = {
        [14] = {
            passives  = { "CircleOfTheMoon_14_LunarForm" },
        },
    },
}

M.subclasses["CircleOfTheSea"] = {
    parent = "Druid",
    levels = {
        [14] = {
            passives  = { "CircleOfTheSea_14_OceanicGift" },
        },
    },
}

M.subclasses["ClockworkSorcery"] = {
    parent = "Sorcerer",
    levels = {
        [11] = {
            passives  = {},
        },
        [14] = {
            passives  = { "TranceOfOrder" },
        },
        [18] = {
            passives  = { "ClockworkSorcery_18_ClockworkCavalcade" },
        },
    },
}

M.subclasses["ConjurationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(a29ca5bb-3d26-4447-8ff5-12e9ed51a980,1,0,ConjurationSavant,,,AlwaysPrepared)",
        },
        [14] = {
            passives  = { "Conjurer_14_SplinteredSummons" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(a29ca5bb-3d26-4447-8ff5-12e9ed51a980,1,0,ConjurationSavant,,,AlwaysPrepared)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(a29ca5bb-3d26-4447-8ff5-12e9ed51a980,1,0,ConjurationSavant,,,AlwaysPrepared)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectSpells(a29ca5bb-3d26-4447-8ff5-12e9ed51a980,1,0,ConjurationSavant,,,AlwaysPrepared)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["DanceCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "Evasion" },
        },
    },
}

M.subclasses["DeathDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "DeathDomain_17_ImprovedReaper" },
        },
    },
}

M.subclasses["Devotion"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "Devotion_15_SmiteOfProtection" },
        },
        [20] = {
            passives  = { "Devotion_20_HolyNimbus" },
        },
    },
}

M.subclasses["DevourerGuild"] = {
    parent = "MonsterHunter",
    levels = {
        [15] = {
            passives  = { "DevourerGuild_15_RavenousMight" },
        },
        [18] = {
            passives  = { "DevourerGuild_18_ApexMetabolism" },
        },
    },
}

M.subclasses["DivinationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(8e445849-3d0f-4cce-8f9c-b162e3e03ba2,1,0,DivinationSavant,,,AlwaysPrepared)",
        },
        [14] = {
            passives  = { "Diviner_14_GreaterPortent" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(8e445849-3d0f-4cce-8f9c-b162e3e03ba2,1,0,DivinationSavant,,,AlwaysPrepared)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(8e445849-3d0f-4cce-8f9c-b162e3e03ba2,1,0,DivinationSavant,,,AlwaysPrepared)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectSpells(8e445849-3d0f-4cce-8f9c-b162e3e03ba2,1,0,DivinationSavant,,,AlwaysPrepared)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["DraconicBloodline"] = {
    parent = "Sorcerer",
    levels = {
        [14] = {
            passives  = { "DraconicBloodline_14_DragonWings" },
        },
        [18] = {
            passives  = { "DraconicBloodline_18_DragonCompanion" },
            boosts    = "ActionResource(DraconicSpiritCharge,1,0)",
        },
    },
}

M.subclasses["EldritchKnight"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "ArcaneCharge" },
        },
        [18] = {
            passives  = { "EldritchKnight_ImprovedWarMagic" },
        },
    },
}

M.subclasses["EnchantmentSchool"] = {
    parent = "Wizard",
    levels = {
        [6] = {
            passives  = { "SplitEnchantment" },
        },
        [10] = {
            passives  = {},
        },
        [13] = {
            passives  = {},
            selectors = "SelectSpells(c930bb09-0c28-4683-ac8e-49ee3262338b,1,0,EnchantmentSavant,,,AlwaysPrepared)",
        },
        [14] = {
            passives  = { "Enchanter_14_AlterMemories" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(c930bb09-0c28-4683-ac8e-49ee3262338b,1,0,EnchantmentSavant,,,AlwaysPrepared)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(c930bb09-0c28-4683-ac8e-49ee3262338b,1,0,EnchantmentSavant,,,AlwaysPrepared)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectSpells(c930bb09-0c28-4683-ac8e-49ee3262338b,1,0,EnchantmentSavant,,,AlwaysPrepared)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["EvocationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(0260a3ae-9ff6-4e24-a081-506f6db2ebf3,1,0,EvocationSavant,,,AlwaysPrepared)",
        },
        [14] = {
            passives  = { "Evoker_14_Overchannel" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(0260a3ae-9ff6-4e24-a081-506f6db2ebf3,1,0,EvocationSavant,,,AlwaysPrepared)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(0260a3ae-9ff6-4e24-a081-506f6db2ebf3,1,0,EvocationSavant,,,AlwaysPrepared)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectSpells(0260a3ae-9ff6-4e24-a081-506f6db2ebf3,1,0,EvocationSavant,,,AlwaysPrepared)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["FeyWanderer"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "FeyWanderer_15_MistyWanderer" },
        },
    },
}

M.subclasses["Fiend"] = {
    parent = "Warlock",
    levels = {
        [14] = {
            passives  = { "Fiend_14_HurlThroughHell" },
            boosts    = "ActionResource(HurlThroughHellCharge,1,0)",
        },
    },
}

M.subclasses["FourElements"] = {
    parent = "Monk",
    levels = {
        [17] = {
            passives  = { "FourElements_17_ElementalEpitome" },
        },
    },
}

M.subclasses["GlamourCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = {},
            selectors = "AddSpells(8ad26d20-d989-4195-9af0-818a86dfed07,,,,AlwaysPrepared)",
        },
    },
}

M.subclasses["GloomStalker"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "GloomStalker_15_ShadowyDodge" },
        },
    },
}

M.subclasses["Glory"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "Glory_15_GloriousDefense" },
        },
        [20] = {
            passives  = { "Glory_20_LivingLegend" },
        },
    },
}

M.subclasses["GraveDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "GraveDomain_17_KeeperOfSouls" },
        },
    },
}

M.subclasses["GreatOldOne"] = {
    parent = "Warlock",
    levels = {
        [14] = {
            passives  = { "GreatOldOne_14_CreateThrall" },
        },
    },
}

M.subclasses["Hellspeaker"] = {
    parent = "Illrigger",
    levels = {
        [15] = {
            passives  = { "Hellspeaker_15_QuidProQuo" },
        },
        [18] = {
            passives  = { "Hellspeaker_18_Incontrovertible" },
        },
    },
}

M.subclasses["HighRoller"] = {
    parent = "Gunslinger",
    levels = {
        [14] = {
            passives  = { "HighRoller_14_DoubleOrNothing" },
        },
        [15] = {
            passives  = { "HighRoller_15_StackedDeck" },
        },
        [18] = {
            passives  = { "HighRoller_18_Jackpot" },
        },
    },
}

M.subclasses["Hunter"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "Hunter_15_SuperiorHuntersDefense" },
        },
    },
}

M.subclasses["IllusionSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(b4308398-d948-4ef1-a0d5-9da1da860917,1,0,IllusionSavant,,,AlwaysPrepared)",
        },
        [14] = {
            passives  = { "Illusionist_14_IllusoryReality" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(b4308398-d948-4ef1-a0d5-9da1da860917,1,0,IllusionSavant,,,AlwaysPrepared)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(b4308398-d948-4ef1-a0d5-9da1da860917,1,0,IllusionSavant,,,AlwaysPrepared)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectSpells(b4308398-d948-4ef1-a0d5-9da1da860917,1,0,IllusionSavant,,,AlwaysPrepared)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["KnowledgeDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "KnowledgeDomain_17_DivineForeknowledge" },
        },
    },
}

M.subclasses["LifeDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "LifeDomain_17_SupremeHealing" },
        },
    },
}

M.subclasses["LightDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "LightDomain_17_CoronaOfLight" },
        },
    },
}

M.subclasses["LoreCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "PeerlessSkill" },
        },
    },
}

M.subclasses["Mercy"] = {
    parent = "Monk",
    levels = {
        [17] = {
            passives  = { "Mercy_17_HandOfUltimateMercy" },
        },
    },
}

M.subclasses["MoonCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "MoonCollege_12_EventidesSplendor" },
        },
    },
}

M.subclasses["NecromancySchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(7cb1296f-113c-4fc6-a1c8-e18288aa6360,1,0,NecromancySavant,,,AlwaysPrepared)",
        },
        [14] = {
            passives  = { "Necromancer_14_DeathsMaster" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(7cb1296f-113c-4fc6-a1c8-e18288aa6360,1,0,NecromancySavant,,,AlwaysPrepared)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(7cb1296f-113c-4fc6-a1c8-e18288aa6360,1,0,NecromancySavant,,,AlwaysPrepared)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectSpells(7cb1296f-113c-4fc6-a1c8-e18288aa6360,1,0,NecromancySavant,,,AlwaysPrepared)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["NobleGenies"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "NobleGenies_15_ElementalRebuke" },
        },
        [20] = {
            passives  = { "NobleGenies_20_NobleScion" },
        },
    },
}

M.subclasses["OccultistGuild"] = {
    parent = "MonsterHunter",
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [15] = {
            passives  = { "OccultistGuild_15_SpellbreakerFocus" },
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [18] = {
            passives  = { "OccultistGuild_18_ArcaneNemesis" },
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [20] = {
            passives  = {},
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
    },
}

M.subclasses["OpenHand"] = {
    parent = "Monk",
    levels = {
        [17] = {
            passives  = { "OpenHand_17_QuiveringPalm" },
        },
    },
}

M.subclasses["Painkiller"] = {
    parent = "Illrigger",
    levels = {
        [15] = {
            passives  = { "Painkiller_15_Deathstrike" },
        },
        [18] = {
            passives  = { "Painkiller_18_DispatersSupremacy" },
        },
    },
}

M.subclasses["PsiWarrior"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "PsiWarrior_12_BulwarkOfForce" },
        },
        [18] = {
            passives  = { "PsiWarrior_TelekineticMaster" },
        },
    },
}

M.subclasses["PurpleDragonKnight"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Banneret_12_SharedResilience" },
        },
        [18] = {
            passives  = { "Banneret_InspiringSurge_Improved" },
        },
    },
}

M.subclasses["RuneKnight"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "RuneKnight_12_MasterOfRunes" },
        },
        [18] = {
            passives  = { "RuneKnight_RunicJuggernaut" },
        },
    },
}

M.subclasses["SanguineKnight"] = {
    parent = "Illrigger",
    levels = {
        [15] = {
            passives  = { "SanguineKnight_15_HaemalExchange" },
        },
        [18] = {
            passives  = { "SanguineKnight_18_BloodForBlood" },
        },
    },
}

M.subclasses["ScionThree"] = {
    parent = "Rogue",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "DeadThree_UnholyInfiltration" },
        },
        [17] = {
            passives  = { "DeadThree_11_MurderousIntent" },
        },
    },
}

M.subclasses["Shadow"] = {
    parent = "Monk",
    levels = {
        [17] = {
            passives  = { "Shadow_17_CloakOfShadows" },
        },
    },
}

M.subclasses["Shadowmaster"] = {
    parent = "Illrigger",
    levels = {
        [15] = {
            passives  = { "Shadowmaster_Illrigger_15_DoomedToTheShadows" },
        },
        [18] = {
            passives  = { "Shadowmaster_Illrigger_18_DarkMalediction" },
        },
    },
}

M.subclasses["Soulknife"] = {
    parent = "Rogue",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "SoulKnife_PsychicVeil" },
        },
        [17] = {
            passives  = { "SoulKnife_11_RendMind" },
        },
    },
}

M.subclasses["SpellfireSorcery"] = {
    parent = "Sorcerer",
    levels = {
        [11] = {
            passives  = {},
        },
        [14] = {
            passives  = { "Spellfire_11_HonedSpellfire" },
        },
        [18] = {
            passives  = { "SpellfireSorcery_18_CrownOfSpellfire" },
        },
    },
}

M.subclasses["Spellslinger"] = {
    parent = "Gunslinger",
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,2)",
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [14] = {
            passives  = { "Spellslinger_14_MagicBullet" },
        },
        [15] = {
            passives  = { "SpellSlinger_15_ArcaneBarrage" },
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [16] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [18] = {
            passives  = { "SpellSlinger_18_SpellStorm" },
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [20] = {
            passives  = {},
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
    },
}

M.subclasses["SwordsCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "SwordsCollege_12_MastersFlourish" },
        },
    },
}

M.subclasses["Thief"] = {
    parent = "Rogue",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "Thief_UseMagicDevice" },
        },
        [17] = {
            passives  = { "Thief_11_ThiefReflexes" },
        },
    },
}

M.subclasses["TotemWarriorPath"] = {
    parent = "Barbarian",
    levels = {
        [14] = {
            passives  = {},
            selectors = "SelectPassives(22222222-2222-2222-2222-222222220001,1,PowerOfTheWilds)",
        },
    },
}

M.subclasses["TransmutationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(538dd943-cd46-4140-a75e-d51b747c1367,1,0,TransmutationSavant,,,AlwaysPrepared)",
        },
        [14] = {
            passives  = { "Transmuter_14_MasterTransmuter" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(538dd943-cd46-4140-a75e-d51b747c1367,1,0,TransmutationSavant,,,AlwaysPrepared)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(538dd943-cd46-4140-a75e-d51b747c1367,1,0,TransmutationSavant,,,AlwaysPrepared)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectSpells(538dd943-cd46-4140-a75e-d51b747c1367,1,0,TransmutationSavant,,,AlwaysPrepared)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["TrickeryDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "TrickeryDomain_17_ImprovedDuplicity" },
        },
    },
}

M.subclasses["ValorCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "BattleMagic" },
        },
    },
}

M.subclasses["Vengeance"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "Vengeance_15_SoulOfVengeance" },
        },
        [20] = {
            passives  = { "Vengeance_20_AvengingAngel" },
        },
    },
}

M.subclasses["WarDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "WarDomain_17_AvatarOfBattle" },
        },
    },
}

M.subclasses["WhiteHat"] = {
    parent = "Gunslinger",
    levels = {
        [14] = {
            passives  = { "WhiteHat_14_GoldStarHero" },
        },
        [15] = {
            passives  = { "WhiteHat_15_Peacekeeper" },
        },
        [18] = {
            passives  = { "WhiteHat_18_LawgiversReach" },
        },
    },
}

M.subclasses["WildMagic"] = {
    parent = "Sorcerer",
    levels = {
        [11] = {
            passives  = {},
        },
        [14] = {
            passives  = { "ControlledChaos" },
        },
        [18] = {
            passives  = { "WildMagic_18_TamedSurge" },
        },
    },
}

M.subclasses["WildMagicPath"] = {
    parent = "Sorcerer",
    levels = {
        [14] = {
            passives  = { "WildMagic_14_ControlledSurge" },
        },
    },
}

M.subclasses["WinterWalker"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "WinterWalker_15_FrozenHaunt" },
        },
    },
}

M.subclasses["WorldTreePath"] = {
    parent = "Barbarian",
    levels = {
        [14] = {
            passives  = { "WorldTree_14_TravelAlongTheTree" },
        },
    },
}

M.subclasses["ZealotPath"] = {
    parent = "Barbarian",
    levels = {
        [14] = {
            passives  = { "Zealot_14_RageOfTheGods" },
        },
    },
}

_G.ApotheosisClassExpectations = M
return M
