-- AUTO-GENERATED by Scripts/generate_wizard_expectations_lua.py
-- DO NOT EDIT BY HAND.  Re-run the generator after manifest or progression changes.
-- Loaded by BootstrapServer.lua at runtime via require('WizardManifestExpectations').

local M = {}

-- wizard_class_guid identifies the base Wizard class.
M.wizard_class_guid = "a865965f-501b-46e9-9eaa-7748e8c04d09"

-- M.subclasses[subclassName] = {
--   manifest_kind  = 'canonical' | 'inferred'
--   subclass_guid  = '...'
--   levels[N] = {
--     base_passives     = { ... }  -- granted by Wizard base at this level
--     subclass_passives = { ... }  -- granted by the subclass at this level
--   }
-- }
M.subclasses = {}

M.subclasses["AbjurationSchool"] = {
    manifest_kind = "canonical",
    subclass_guid = "e6a0eb75-7a01-4f40-8563-24ba2615e99b",
    levels = {
        [13] = {
            base_passives     = { "UnlockedSpellSlotLevel7" },
            subclass_passives = {},
        },
        [14] = {
            base_passives     = {},
            subclass_passives = { "Abjurer_14_SpellResistance" },
        },
        [15] = {
            base_passives     = { "UnlockedSpellSlotLevel8" },
            subclass_passives = {},
        },
        [16] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [17] = {
            base_passives     = { "UnlockedSpellSlotLevel9" },
            subclass_passives = {},
        },
        [18] = {
            base_passives     = { "SpellMastery" },
            subclass_passives = {},
        },
        [19] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [20] = {
            base_passives     = { "Wizard_SignatureSpells" },
            subclass_passives = {},
        },
    },
}

M.subclasses["BladesingingSchool"] = {
    manifest_kind = "inferred",
    subclass_guid = "8047cf29-2c79-4f12-a4bf-d965a023be63",
    levels = {
        [13] = {
            base_passives     = { "UnlockedSpellSlotLevel7" },
            subclass_passives = {},
        },
        [14] = {
            base_passives     = {},
            subclass_passives = { "SongVictory" },
        },
        [15] = {
            base_passives     = { "UnlockedSpellSlotLevel8" },
            subclass_passives = {},
        },
        [16] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [17] = {
            base_passives     = { "UnlockedSpellSlotLevel9" },
            subclass_passives = {},
        },
        [18] = {
            base_passives     = { "SpellMastery" },
            subclass_passives = {},
        },
        [19] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [20] = {
            base_passives     = { "Wizard_SignatureSpells" },
            subclass_passives = {},
        },
    },
}

M.subclasses["DivinationSchool"] = {
    manifest_kind = "canonical",
    subclass_guid = "7577b0e1-a517-4f82-8f72-05a227dc5e88",
    levels = {
        [13] = {
            base_passives     = { "UnlockedSpellSlotLevel7" },
            subclass_passives = {},
        },
        [14] = {
            base_passives     = {},
            subclass_passives = { "Diviner_14_GreaterPortent" },
        },
        [15] = {
            base_passives     = { "UnlockedSpellSlotLevel8" },
            subclass_passives = {},
        },
        [16] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [17] = {
            base_passives     = { "UnlockedSpellSlotLevel9" },
            subclass_passives = {},
        },
        [18] = {
            base_passives     = { "SpellMastery" },
            subclass_passives = {},
        },
        [19] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [20] = {
            base_passives     = { "Wizard_SignatureSpells" },
            subclass_passives = {},
        },
    },
}

M.subclasses["EvocationSchool"] = {
    manifest_kind = "canonical",
    subclass_guid = "c059dca1-c17d-4dce-8260-83ede5070eac",
    levels = {
        [13] = {
            base_passives     = { "UnlockedSpellSlotLevel7" },
            subclass_passives = {},
        },
        [14] = {
            base_passives     = {},
            subclass_passives = { "Evoker_14_Overchannel" },
        },
        [15] = {
            base_passives     = { "UnlockedSpellSlotLevel8" },
            subclass_passives = {},
        },
        [16] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [17] = {
            base_passives     = { "UnlockedSpellSlotLevel9" },
            subclass_passives = {},
        },
        [18] = {
            base_passives     = { "SpellMastery" },
            subclass_passives = {},
        },
        [19] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [20] = {
            base_passives     = { "Wizard_SignatureSpells" },
            subclass_passives = {},
        },
    },
}

M.subclasses["IllusionSchool"] = {
    manifest_kind = "canonical",
    subclass_guid = "436c9e1a-3a39-48dd-b753-7cee1bd19c00",
    levels = {
        [13] = {
            base_passives     = { "UnlockedSpellSlotLevel7" },
            subclass_passives = {},
        },
        [14] = {
            base_passives     = {},
            subclass_passives = { "Illusionist_14_IllusoryReality" },
        },
        [15] = {
            base_passives     = { "UnlockedSpellSlotLevel8" },
            subclass_passives = {},
        },
        [16] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [17] = {
            base_passives     = { "UnlockedSpellSlotLevel9" },
            subclass_passives = {},
        },
        [18] = {
            base_passives     = { "SpellMastery" },
            subclass_passives = {},
        },
        [19] = {
            base_passives     = {},
            subclass_passives = {},
        },
        [20] = {
            base_passives     = { "Wizard_SignatureSpells" },
            subclass_passives = {},
        },
    },
}

return M
