"""Generate the Indomitable Might floor statuses (Barbarian 18, PHB 2024) - issue #22.

PHB 2024: if your total for a Strength check or saving throw is less than your Strength score, use the score.
The engine can only floor the d20 (MinimumRollResult), so the floor that makes the total equal the score is
score - (the roll's own bonus). ScriptExtender/Lua/IndomitableMight.lua computes it per Barbarian (Strength save,
Athletics, plain Strength check) and applies one APO_IM_<TYPE>_<n> status of each type.

Why statuses with one short boost each: a single passive with 57 IF() boosts hung the game during module load
(bisected 2026-09-30), and stats can't take the floor from an expression.

Strength SAVES (2026-10-02): MinimumRollResult floors only ~5/8 real saves, so APO_IM_SAVE_<n> instead unlocks
Interrupt_IndomitableMight_<n> (OnPostRoll, SetRoll(n)): on a failed Strength save it sets the d20 to n, so the
total is exactly the Strength score - a success only if the score meets the DC. Verified in game vs a
real Shadow's native Strength Drain (2/2 failed rolls rescued; control 3/3 landed). Note: interrupts never fire on
script-added (Osi.AddSpell) spells or Osiris casts - test with a creature's native spells.

Owns (rewritten every run): Stats/Generated/Data/Status_IndomitableMight.txt, Interrupt_IndomitableMight.txt
Run: python3 Scripts/gen_indomitable_might.py
"""
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = glob.glob(os.path.join(ROOT, "Public", "*", "Stats", "Generated", "Data"))[0]
FLOORS = range(2, 21)  # a floor of 1 changes nothing; above 20 can't happen below Strength 30
TYPES = {
    "SAVE": None,  # an interrupt per floor (see the docstring), not a boost
    "ATH": ("IsSkillChecked(Skill.Athletics)", "SkillCheck"),
    "STR": ("IsAbilityChecked(Ability.Strength)", "RawAbility"),
}

lines = ["// GENERATED by Scripts/gen_indomitable_might.py - do not edit by hand (#22).",
         "// One status per roll type and d20 floor; IndomitableMight.lua applies the right ones.", ""]
for key, spec in TYPES.items():
    for n in FLOORS:
        boost = (f"UnlockInterrupt(Interrupt_IndomitableMight_{n})" if spec is None
                 else f"IF({spec[0]}):MinimumRollResult({spec[1]},{n})")
        lines += [f'new entry "APO_IM_{key}_{n}"', 'type "StatusData"', 'data "StatusType" "BOOST"',
                  f'data "StackId" "APO_IM_{key}"',
                  f'data "Boosts" "{boost}"',
                  'data "StatusPropertyFlags" "DisableOverhead;DisableCombatlog;DisablePortraitIndicator;IgnoreResting;ApplyToDead"',
                  'data "StatusGroups" "SG_RemoveOnRespec"', ""]
with open(os.path.join(OUT, "Status_IndomitableMight.txt"), "w", encoding="utf-8", newline="\r\n") as f:
    f.write("\n".join(lines))
ints = ["// GENERATED by Scripts/gen_indomitable_might.py - do not edit by hand (#22).",
        "// Indomitable Might, Strength saves: set the d20 so the total equals the Strength score, if that succeeds.", ""]
for n in FLOORS:
    ints += [f'new entry "Interrupt_IndomitableMight_{n}"', 'type "InterruptData"',
             'data "DisplayName" "ha6c7d8e900000000000000000000013"', 'data "Description" "ha6c7d8ea00000000000000000000014"',
             'data "Icon" "PassiveFeature_RelentlessRage"', 'data "InterruptContext" "OnPostRoll"',
             'data "InterruptContextScope" "Self"', 'data "Container" "YesNoDecision"',
             'data "Conditions" "Self(context.Target,context.Observer) and HasInterruptedSavingThrow() and '
             # any failed Strength save (IsSetInterruptInteresting(n) never fired - it seems to read n as the total);
             # SetRoll(n) then makes the total exactly the score, which succeeds only if the score beats the DC
             'HasSavingThrowWithAbility(Ability.Strength) and not AnyEntityIsItem() and IsFlatValueInterruptInteresting(30)"',
             f'data "Properties" "SetRoll({n})"', 'data "InterruptDefaultValue" "Enabled"', ""]
with open(os.path.join(OUT, "Interrupt_IndomitableMight.txt"), "w", encoding="utf-8", newline="\r\n") as f:
    f.write("\n".join(ints))
print(f"wrote {len(TYPES) * len(FLOORS)} statuses, {len(FLOORS)} interrupts")
