"""Generate the Indomitable Might floor statuses (Barbarian 18, PHB 2024) - issue #22.

PHB 2024: if your total for a Strength check or saving throw is less than your Strength score, use the score.
The engine can only floor the d20 (MinimumRollResult), so the floor that makes the total equal the score is
score - (the roll's own bonus). ScriptExtender/Lua/IndomitableMight.lua computes it per Barbarian (Strength save,
Athletics, plain Strength check) and applies one APO_IM_<TYPE>_<n> status of each type.

Why statuses with one short boost each: a single passive with 57 IF() boosts hung the game during module load
(bisected 2026-09-30), and stats can't take the floor from an expression.

Owns (rewritten every run): Stats/Generated/Data/Status_IndomitableMight.txt
Run: python3 Scripts/gen_indomitable_might.py
"""
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = glob.glob(os.path.join(ROOT, "Public", "*", "Stats", "Generated", "Data"))[0]
FLOORS = range(2, 21)  # a floor of 1 changes nothing; above 20 can't happen below Strength 30
TYPES = {
    # saves: a spell/effect save carries its ability in the hit (HasSavingThrowWithAbility, as base Starry Form:
    # Dragon); checks set CheckedAbility. IsAbilityChecked alone never matched a save (tested 2026-09-30).
    "SAVE": ("HasSavingThrowWithAbility(Ability.Strength) or IsAbilityChecked(Ability.Strength)", "SavingThrow"),
    "ATH": ("IsSkillChecked(Skill.Athletics)", "SkillCheck"),
    "STR": ("IsAbilityChecked(Ability.Strength)", "RawAbility"),
}

lines = ["// GENERATED by Scripts/gen_indomitable_might.py - do not edit by hand (#22).",
         "// One status per roll type and d20 floor; IndomitableMight.lua applies the right ones.", ""]
for key, (cond, roll) in TYPES.items():
    for n in FLOORS:
        lines += [f'new entry "APO_IM_{key}_{n}"', 'type "StatusData"', 'data "StatusType" "BOOST"',
                  f'data "StackId" "APO_IM_{key}"',
                  f'data "Boosts" "IF({cond}):MinimumRollResult({roll},{n})"',
                  'data "StatusPropertyFlags" "DisableOverhead;DisableCombatlog;DisablePortraitIndicator;IgnoreResting;ApplyToDead"',
                  'data "StatusGroups" "SG_RemoveOnRespec"', ""]
with open(os.path.join(OUT, "Status_IndomitableMight.txt"), "w", encoding="utf-8", newline="\r\n") as f:
    f.write("\n".join(lines))
print(f"wrote {len(TYPES) * len(FLOORS)} statuses")
