"""Shared helpers for the class generators (gen_illrigger.py, ...): stats entries, loca handles, idempotent
patches of Progressions / ActionResourceDefinitions / LevelMapValues / PassiveLists / loca between markers."""
import glob
import os
import re
import uuid

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUB = glob.glob(os.path.join(REPO, "Public", "*"))[0]
DATA = os.path.join(PUB, "Stats", "Generated", "Data")
LOCA = glob.glob(os.path.join(REPO, "Mods", "*", "Localization", "English", "PHB2024-Apotheosis.xml"))[0]
DND = glob.glob(os.path.join(REPO, "..", "dnd55e", "Public", "DnD2024*"))[0]
NODE_RE = re.compile(r'[ \t]*<node id="Progression">(?:(?!</node>).)*?</node>\n', re.S)
# A spell with no SpellAnimation (own or inherited) never finishes casting - verified in game 2026-09-30.
SHOUT_ANIM = "9122eb08-93f1-4010-a275-f5ae3ec7c76e,,;,,;9fb11cca-02d4-4d2f-955f-2826c0553b17,,;5103d398-d8de-4aa4-9633-db2e1b7f6254,,;5301d674-b7da-47b6-b4cf-2802ba33a9e9,,;,,;86b3cf93-21fb-4a3d-bed9-97d0a567d084,,;,,;,,"
TARGET_ANIM = "3ff87abf-1ea1-4c32-aadf-c822d74c7dc0,,;,,;ab7b6aac-b3c9-4918-8f17-f777a94dcb5e,,;57211a11-ed0b-46d7-9369-81df25a85df6,,;d8925ce4-d6d9-400c-92f5-ad772ef7f178,,;,,;eadedcce-d01b-4fbb-a1ae-d218f13aa5d6,,;,,;,,"


class Gen:
    def __init__(self, key, marker):
        self.key, self.marker = key, marker
        self.P, self.S, self.SP, self.I = [], [], [], []
        self.loca, self.resources, self.lists, self.levelmaps = {}, [], [], []

    def gid(self, k):
        return str(uuid.uuid5(uuid.NAMESPACE_URL, f"apotheosis-{self.key}:{k}"))

    def h(self, k, text):
        handle = "h" + uuid.uuid5(uuid.NAMESPACE_URL, f"apotheosis-{self.key}-loca:{k}").hex
        self.loca[handle] = text
        return handle

    @staticmethod
    def entry(name, typ, fields, using=None, comment=None):
        out = ([f"// {comment}"] if comment else []) + [f'new entry "{name}"', f'type "{typ}"']
        if using:
            out.append(f'using "{using}"')
        out += [f'data "{k}" "{v}"' for k, v in fields.items() if v is not None]
        return "\n".join(out) + "\n"

    def passive(self, name, title, text, fields=None, icon="PassiveFeature_Generic_Magical", hidden=False, comment=None):
        base = {"DisplayName": self.h(name + ":n", title), "Description": self.h(name + ":d", text), "Icon": icon,
                "Properties": "IsHidden" if hidden else "Highlighted"}
        self.P.append(self.entry(name, "PassiveData", {**base, **(fields or {})}, comment=comment))

    def status(self, name, title, text, fields=None, using=None, icon=None, comment=None):
        base = {"DisplayName": self.h(name + ":n", title)}
        if text:
            base["Description"] = self.h(name + ":d", text)
        if icon:
            base["Icon"] = icon
        if not using:
            base["StatusType"] = "BOOST"
        self.S.append(self.entry(name, "StatusData", {**base, **(fields or {})}, using=using, comment=comment))

    def spell(self, name, title, text, fields, using=None, icon=None, comment=None):
        base = {"DisplayName": self.h(name + ":n", title), "Description": self.h(name + ":d", text)}
        if icon:
            base["Icon"] = icon
        f = {**base, **fields}
        if not using and "SpellAnimation" not in f and "ContainerSpells" not in f:
            f["SpellAnimation"] = SHOUT_ANIM if f.get("SpellType") == "Shout" else TARGET_ANIM
        self.SP.append(self.entry(name, "SpellData", f, using=using, comment=comment))

    def interrupt(self, name, title, text, fields, icon=None, comment=None):
        base = {"DisplayName": self.h(name + ":n", title), "Description": self.h(name + ":d", text)}
        if icon:
            base["Icon"] = icon
        self.I.append(self.entry(name, "InterruptData", {**base, **fields}, comment=comment))

    # ------------------------------------------------------------ writers
    def write_stats(self, prefix, script, issue):
        head = (f"// GENERATED by Scripts/{script} ({issue}) - edit the generator, not this file.\n\n")
        for kind, rows in (("Passive", self.P), ("Status", self.S), ("Spell", self.SP), ("Interrupt", self.I)):
            path = os.path.join(DATA, f"{kind}_{prefix}.txt")
            if rows:
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(head + "\n".join(rows))
            elif os.path.exists(path):
                os.remove(path)

    def _between(self, path, rows):
        block = (f"                <!-- {self.marker} BEGIN (generated) -->\n" + "".join(rows)
                 + f"                <!-- {self.marker} END -->\n")
        s = open(path, encoding="utf-8").read()
        start, end = f"                <!-- {self.marker} BEGIN", f"<!-- {self.marker} END -->\n"
        if start in s:
            s = s[:s.index(start)] + block + s[s.index(end) + len(end):]
        else:
            i = s.rindex("            </children>")
            s = s[:i] + block + s[i:]
        open(path, "w", encoding="utf-8", newline="").write(s)

    def resource(self, name, mx, replenish, title, text):
        self.resources.append(f"""                <node id="ActionResourceDefinition">
                    <attribute id="DisplayName" type="TranslatedString" handle="{self.h('res:' + name + ':n', title)}" version="1"/>
                    <attribute id="Description" type="TranslatedString" handle="{self.h('res:' + name + ':d', text)}" version="1"/>
                    <attribute id="IsHidden" type="bool" value="false"/>
                    <attribute id="MaxLevel" type="uint32" value="0"/>
                    <attribute id="MaxValue" type="uint32" value="{mx}"/>
                    <attribute id="Name" type="FixedString" value="{name}"/>
                    <attribute id="ReplenishType" type="FixedString" value="{replenish}"/>
                    <attribute id="ShowOnActionResourcePanel" type="bool" value="true"/>
                    <attribute id="UUID" type="guid" value="{self.gid('res:' + name)}"/>
                </node>
""")

    def passive_list(self, name, passives):
        u = self.gid("list:" + name)
        self.lists.append(f"""                <node id="PassiveList">
                    <attribute id="Name" type="FixedString" value="{name}"/>
                    <attribute id="Passives" type="LSString" value="{','.join(passives)}"/>
                    <attribute id="UUID" type="guid" value="{u}"/>
                </node>
""")
        return u

    def levelmap(self, name, uuid_, levels, preferred_class=None):
        """A LevelMapSeries; with dnd55e's UUID it replaces dnd55e's series."""
        attrs = [(f"Level{lv}", "LSString", v) for lv, v in sorted(levels.items())]
        attrs += [("Name", "FixedString", name)]
        if preferred_class:
            attrs.append(("PreferredClassUUID", "guid", preferred_class))
        attrs.append(("UUID", "guid", uuid_))
        rows = "".join(f'                    <attribute id="{k}" type="{t}" value="{v}"/>\n' for k, t, v in attrs)
        self.levelmaps.append(f'                <node id="LevelMapSeries">\n{rows}                </node>\n')

    def patch_files(self):
        if self.resources:
            self._between(glob.glob(os.path.join(PUB, "ActionResourceDefinitions", "*.lsx"))[0], self.resources)
        if self.lists:
            self._between(os.path.join(PUB, "Lists", "PassiveLists.lsx"), self.lists)
        if self.levelmaps:
            self._between(os.path.join(PUB, "Levelmaps", "LevelMapValues.lsx"), self.levelmaps)

    def patch_loca(self):
        s = open(LOCA, encoding="utf-8").read()
        s = re.sub(r'  <content contentuid="(h[0-9a-f]{32})" version="\d+">[^<]*</content>\n',
                   lambda m: "" if m.group(1) in self.loca else m.group(0), s)
        esc = lambda t: t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        rows = "".join(f'  <content contentuid="{k}" version="1">{esc(v)}</content>\n' for k, v in self.loca.items())
        i = s.rindex("</contentList>")
        s = s[:i] + rows + s[i:]
        assert "<!--" not in s, "loca must not contain XML comments (Toolkit crash)"
        open(LOCA, "w", encoding="utf-8", newline="").write(s)


def drop_entries(fname, names):
    """Remove whole entries by name from a hand-kept stats file (Passive.txt, ...)."""
    path = os.path.join(DATA, fname)
    s = open(path, encoding="utf-8").read()
    for n in names:
        s = re.sub(rf'(?:\r?\n)*new entry "{n}"\r?\n(?:(?!new entry ).)*', "\n\n", s, flags=re.S)
    s = re.sub(r"\n{3,}", "\n\n", s)
    open(path, "w", encoding="utf-8", newline="").write(s)


def patch_progressions(nodes, new_nodes, marker):
    """nodes: existing uuid -> {attr: value} (PassivesAdded/PassivesRemoved/Boosts/Selectors; None deletes the node).
    new_nodes: [(uuid, name, level, progression_type, table, {attrs})], kept between markers."""
    path = os.path.join(PUB, "Progressions", "Progressions.lsx")
    s = open(path, encoding="utf-8").read()
    seen = set()

    def fix(m):
        b = m.group(0)
        u = re.search(r'id="UUID" type="guid" value="([^"]*)"', b).group(1)
        if u not in nodes:
            return b
        seen.add(u)
        if nodes[u] is None:
            return ""
        ind = re.search(r'\n(\s*)<attribute id="Level"', b).group(1)
        for k in ("PassivesAdded", "PassivesRemoved", "Boosts", "Selectors"):
            b = re.sub(rf'\s*<attribute id="{k}" type="LSString" value="[^"]*"/>', "", b)
        add = "".join(f'\n{ind}<attribute id="{k}" type="LSString" value="{v}"/>' for k, v in nodes[u].items())
        return re.sub(r'(\n\s*<attribute id="Level")', add + r"\1", b, count=1)

    s = NODE_RE.sub(fix, s)
    missing = [u for u, w in nodes.items() if w is not None and u not in seen]
    assert not missing, f"progression nodes not found: {missing}"
    rows = []
    for u, name, level, ptype, table, attrs in new_nodes:
        a = [(k, "LSString", v) for k, v in attrs.items()]
        a += [("Level", "uint8", level), ("Name", "LSString", name), ("ProgressionType", "uint8", ptype),
              ("TableUUID", "guid", table), ("UUID", "guid", u)]
        body = "".join(f'                    <attribute id="{k}" type="{t}" value="{v}"/>\n' for k, t, v in sorted(a, key=lambda x: x[0]))
        rows.append(f'                <node id="Progression">\n{body}                </node>\n')
    block = (f"                <!-- {marker} BEGIN (generated) -->\n" + "".join(rows) + f"                <!-- {marker} END -->\n")
    start, end = f"                <!-- {marker} BEGIN", f"<!-- {marker} END -->\n"
    if start in s:
        s = s[:s.index(start)] + block + s[s.index(end) + len(end):]
    elif rows:
        i = s.rindex("            </children>")
        s = s[:i] + block + s[i:]
    open(path, "w", encoding="utf-8", newline="").write(s)
