"""Generate WizardManifestExpectations.lua from wizard_13_20_expectations.json.

Run this after any change to manifests or Progressions.lsx:
    python Scripts/generate_wizard_expectations_lua.py

Output is committed alongside BootstrapServer.lua and packed into the mod.
The SE runtime loads it as a sibling Lua file; no JSON I/O in the game.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

EXPECTATIONS_JSON = Path("Scripts/test_build_manifests/wizard_13_20_expectations.json")
OUTPUT_LUA = Path(
    "Mods/PHB2024_DND_13-20_PathtoApotheosis_1467c26f-e7bb-49d1-d980-6e033aea04fa"
    "/ScriptExtender/Lua/WizardManifestExpectations.lua"
)


def passives_list(value: str) -> list[str]:
    """Split a semicolon-or-comma-separated passives string into a cleaned list."""
    if not value or not value.strip():
        return []
    parts = [p.strip() for p in value.replace(";", ",").split(",")]
    return [p for p in parts if p]


def lua_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def lua_str_list(items: list[str], indent: int = 6) -> str:
    if not items:
        return "{}"
    pad = " " * indent
    inner = ", ".join(lua_str(i) for i in items)
    return "{ " + inner + " }"


def build_level_table(base_entries: list[dict], sub_entries: list[dict]) -> dict[int, dict]:
    """Merge base wizard and subclass entries into a per-level dict."""
    by_level: dict[int, dict] = {}

    for entry in base_entries:
        lvl = int(entry["level"])
        by_level.setdefault(lvl, {"base_passives": [], "subclass_passives": []})
        by_level[lvl]["base_passives"] = passives_list(entry.get("passives_added", ""))

    for entry in sub_entries:
        lvl = int(entry["level"])
        by_level.setdefault(lvl, {"base_passives": [], "subclass_passives": []})
        by_level[lvl]["subclass_passives"] = passives_list(entry.get("passives_added", ""))

    return by_level


def emit_lua(data: dict) -> str:
    lines: list[str] = []

    lines.append("-- AUTO-GENERATED by Scripts/generate_wizard_expectations_lua.py")
    lines.append("-- DO NOT EDIT BY HAND.  Re-run the generator after manifest or progression changes.")
    lines.append("-- Loaded by BootstrapServer.lua at runtime via Ext.Require('WizardManifestExpectations.lua')")
    lines.append("-- and exposed as _G.WizardManifestExpectations for compatibility.")
    lines.append("")
    lines.append("local M = {}")
    lines.append("")
    lines.append("-- wizard_class_guid identifies the base Wizard class.")
    lines.append(f"M.wizard_class_guid = {lua_str(data['wizard_class_guid'])}")
    lines.append("")
    lines.append("-- M.subclasses[subclassName] = {")
    lines.append("--   manifest_kind  = 'canonical' | 'inferred'")
    lines.append("--   subclass_guid  = '...'")
    lines.append("--   levels[N] = {")
    lines.append("--     base_passives     = { ... }  -- granted by Wizard base at this level")
    lines.append("--     subclass_passives = { ... }  -- granted by the subclass at this level")
    lines.append("--   }")
    lines.append("-- }")
    lines.append("M.subclasses = {}")
    lines.append("")

    for sub in data["subclasses"]:
        name = sub["subclass_name"]
        kind = sub.get("manifest_kind", "canonical")
        guid = sub.get("subclass_guid", "")

        by_level = build_level_table(
            sub.get("expected_wizard_base_13_20", []),
            sub.get("expected_subclass_13_20", []),
        )

        lines.append(f"M.subclasses[{lua_str(name)}] = {{")
        lines.append(f"    manifest_kind = {lua_str(kind)},")
        lines.append(f"    subclass_guid = {lua_str(guid)},")
        lines.append("    levels = {")

        for lvl in sorted(by_level.keys()):
            entry = by_level[lvl]
            base_p = lua_str_list(entry["base_passives"], indent=8)
            sub_p = lua_str_list(entry["subclass_passives"], indent=8)
            lines.append(f"        [{lvl}] = {{")
            lines.append(f"            base_passives     = {base_p},")
            lines.append(f"            subclass_passives = {sub_p},")
            lines.append("        },")

        lines.append("    },")
        lines.append("}")
        lines.append("")

    lines.append("_G.WizardManifestExpectations = M")
    lines.append("return M")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    if not EXPECTATIONS_JSON.exists():
        print(f"ERROR: {EXPECTATIONS_JSON} not found. Run build_wizard_13_20_expectations.py first.")
        return 1

    data = json.loads(EXPECTATIONS_JSON.read_text(encoding="utf-8"))
    lua_source = emit_lua(data)

    OUTPUT_LUA.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_LUA.write_text(lua_source, encoding="utf-8")

    print(f"Wrote {OUTPUT_LUA}")
    print(f"Subclasses: {', '.join(s['subclass_name'] for s in data['subclasses'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
